USE [master]
GO

/****** Object:  Database [cliente2]    Script Date: 26/03/2020 21:54:48 ******/
CREATE DATABASE [cliente2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'cliente2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER01\MSSQL\DATA\cliente2.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'cliente2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER01\MSSQL\DATA\cliente2_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [cliente2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [cliente2] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [cliente2] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [cliente2] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [cliente2] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [cliente2] SET ARITHABORT OFF 
GO

ALTER DATABASE [cliente2] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [cliente2] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [cliente2] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [cliente2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [cliente2] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [cliente2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [cliente2] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [cliente2] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [cliente2] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [cliente2] SET  DISABLE_BROKER 
GO

ALTER DATABASE [cliente2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [cliente2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [cliente2] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [cliente2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [cliente2] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [cliente2] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [cliente2] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [cliente2] SET RECOVERY FULL 
GO

ALTER DATABASE [cliente2] SET  MULTI_USER 
GO

ALTER DATABASE [cliente2] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [cliente2] SET DB_CHAINING OFF 
GO

ALTER DATABASE [cliente2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [cliente2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [cliente2] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [cliente2] SET QUERY_STORE = OFF
GO

ALTER DATABASE [cliente2] SET  READ_WRITE 
GO

USE [cliente2]
GO

/****** Object:  Table [dbo].[cad_cliente4]    Script Date: 26/03/2020 21:56:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[cad_cliente4](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nome] [varchar](255) NOT NULL,
	[numero] [int] NOT NULL
) ON [PRIMARY]
GO


